name: Deploy (Production)

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # PHP
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"

      - run: composer install --no-dev --optimize-autoloader --no-interaction

      # Frontend
      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - run: npm ci && npm run build

      # Clean deploy folder
      - name: Prepare deployment
        run: |
          mkdir deploy
          rsync -av \
            --exclude='.git' \
            --exclude='.github' \
            --exclude='node_modules' \
            --exclude='tests' \
            --exclude='.env' \
            ./ deploy/

      # SSH
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add host
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      # 🚀 Deploy to PRODUCTION
      - name: Deploy to production
        run: |
          rsync -avz --delete \
            --exclude='uploads' \
            -e "ssh -p ${{ secrets.SSH_PORT }}" \
            ./deploy/ \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.SSH_REMOTE_PATH_PRODUCTION }}